import re

hr_name_dict = {
'Boise St.': 'Boise State',
'Penn St.': 'Penn State',
'Wichita St.': 'Wichita State',
'Indiana St.': 'Indiana State',
'Gardner Webb': 'Gardner-Webb',
'Saint Joseph\'s': 'St. Joseph\'s',
'Missouri St.': 'Missouri State',
'East Tennessee St.': 'East Tennessee State',
'USC Upstate': 'SC Upstate',
'Arkansas St.': 'Arkansas State',
'Chicago St.': 'Chicago State',
'Texas A&M Commerce': 'Texas A&M–Commerce',
'Loyola MD': 'Loyola Maryland',
'Arizona St.': 'Arizona State',
'Youngstown St.': 'Youngstown State',
'Wright St.': 'Wright State',
'Montana St.': 'Montana State',
'UT Arlington': 'Texas Arlington',
'Long Beach St.': 'Long Beach State',
'Cal St. Bakersfield': 'CSU Bakersfield',
'Jacksonville St.': 'Jacksonville State',
'St. Thomas': 'St. Thomas (MN)',
'Nebraska Omaha': 'Omaha',
'Sam Houston St.': 'Sam Houston State',
'Tennessee Martin': 'UT Martin',
'Tarleton St.': 'Tarleton State',
'Appalachian St.': 'Appalachian State',
'Georgia St.': 'Georgia State',
'UMKC': 'Kansas City',
'New Mexico St.': 'New Mexico State',
'Morehead St.': 'Morehead State',
'Tennessee St.': 'Tennessee State',
'Oregon St.': 'Oregon State',
'Texas St.': 'Texas State',
'Cal St. Fullerton': 'Cal State Fullerton',
'Utah Valley': 'Utah Valley State',
'Stephen F. Austin': 'Stephen F Austin',
'Fort Wayne': 'IPFW',
'UT Rio Grande Valley': 'Texas Rio Grande Valley',
'Cal St. Northridge': 'CSU Northridge',
'Little Rock': 'Arkansas Little Rock',
'Weber St.': 'Weber State',
'North Dakota St.': 'North Dakota State',
'South Dakota St.': 'South Dakota State',
'Kennesaw St.': 'Kennesaw State',
'Idaho St.': 'Idaho State',
'LIU Brooklyn': 'Long Island',
'Cleveland St.': 'Cleveland State',
'Detroit': 'Detroit Mercy',
'St. Francis PA': 'St. Francis (PA)',
'Ohio St.': 'Ohio State',
'Penn': 'Pennsylvania',
'San Jose St.': 'San Jose State',
'Kent St.': 'Kent State',
'Iowa St.': 'Iowa State',
'Mississippi': 'Ole Miss',
'Washington St.': 'Washington State',
'Mississippi St.': 'Mississippi State',
'Utah St.': 'Utah State',
'San Diego St.': 'San Diego St',
'Miami FL': 'Miami (FL)',
'Kansas St.': 'Kansas State',
'Oklahoma St.': 'Oklahoma State',
'Cal Baptist': 'California Baptist',
'Massachusetts': 'UMass',
'Michigan St.': 'Michigan State',
'North Carolina St.': 'NC State',
'Ball St.': 'Ball State',
'Grambling St.': 'Grambling State',
'Florida St.': 'Florida State',
'Murray St.': 'Murray State',
'Coppin St.': 'Coppin State',
'Delaware St.': 'Delaware State',
'Morgan St.': 'Morgan State',
'Alcorn St.': 'Alcorn State',
'McNeese St.': 'McNeese State',
'Sacramento St.': 'Sacramento State',
'Colorado St.': 'Colorado State',
'Fresno St.': 'Fresno State',
'Illinois St.': 'Illinois State',
'Jackson St.': 'Jackson State',
'Texas A&M Corpus Chris': 'Texas A&M-Corpus Christi',
'Alabama St.': 'Alabama State',
'Miami OH': 'Miami (OH)',
'Norfolk St.': 'Norfolk State',
'Northwestern St.': 'Northwestern State',
'Nicholls St.': 'Nicholls State',
'South Carolina St.': 'South Carolina State',
'Bethune Cookman': 'Bethune-Cookman',
'Southeast Missouri St.': 'Southeast Missouri State',
'Portland St.': 'Portland State',
'Southeastern Louisiana': 'SE Louisiana',
'North Carolina Central': 'NC Central',
'Mississippi Valley St.': 'Mississippi Valley',
'Arkansas Pine Bluff': 'Arkansas-Pine Bluff',
'N.C. State': 'NC State',
'Louisiana': 'Louisiana Lafayette',
'LIU': 'Long Island',
'IU Indy': 'IUPUI',
'Saint Francis': 'St. Francis (PA)',
'Purdue Fort Wayne': 'IPFW',
'Texas A&M–Commerce': 'East Texas A&M',
'Texas A&M-Commerce': 'East Texas A&M',
'Texas A&M Commerce': 'East Texas A&M',
'Mercyhurst': 'Mercyhurst Lakers',
'Charleston': 'College of Charleston',
'West Georgia': 'West Georgia'
}

inv_convert = {v: k for k, v in hr_name_dict.items()}

def convert_name_invert(hr_name):
    if hr_name in inv_convert.keys():
        return inv_convert[hr_name]
    else:
        return hr_name

def convert_name(non_hr_name):
    if non_hr_name in hr_name_dict.keys():
        return hr_name_dict[non_hr_name]
    else:
        return non_hr_name
